# Generated by Django 3.1 on 2020-08-26 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key_Type',
            fields=[
                ('KT_id', models.AutoField(primary_key=True, serialize=False)),
                ('KT_key_desc', models.TextField(default='desc of key type')),
            ],
            options={
                'db_table': 'Key_Type',
            },
        ),
        migrations.CreateModel(
            name='Match_Method_Type',
            fields=[
                ('MMT_id', models.AutoField(primary_key=True, serialize=False)),
                ('MMT_type_desc', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'Match_Method_Type',
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('PAT_id', models.AutoField(primary_key=True, serialize=False)),
                ('PAT_key', models.CharField(db_index=True, default='the key string of the pattern', max_length=4096)),
                ('PAT_graph', models.BinaryField()),
                ('PAT_order', models.IntegerField()),
                ('PAT_name', models.CharField(max_length=45, null=True)),
                ('PAT_desc', models.CharField(max_length=4096, null=True)),
                ('PAT_png', models.BinaryField()),
            ],
            options={
                'db_table': 'Pattern',
            },
        ),
        migrations.CreateModel(
            name='Topology_Type',
            fields=[
                ('TT_id', models.AutoField(primary_key=True, serialize=False)),
                ('TT_type', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Topology_Type',
            },
        ),
        migrations.CreateModel(
            name='Topology',
            fields=[
                ('TOP_id', models.AutoField(primary_key=True, serialize=False)),
                ('TOP_name', models.CharField(db_index=True, max_length=100, null=True)),
                ('TOP_version', models.CharField(max_length=10, null=True)),
                ('TOP_input_shape', models.CharField(max_length=45, null=True)),
                ('TOP_graph', models.BinaryField()),
                ('TOP_source_url', models.URLField(max_length=250, null=True)),
                ('TOP_cost', models.FloatField(db_index=True)),
                ('TOP_desc', models.TextField(default='desc of the topology', null=True)),
                ('TOP_png', models.BinaryField()),
                ('TOP_order', models.IntegerField(db_index=True)),
                ('TOP_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mining.topology_type')),
            ],
            options={
                'db_table': 'Topology',
            },
        ),
        migrations.CreateModel(
            name='Pattern_Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PS_pattern', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mining.pattern')),
                ('PS_topology', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mining.topology')),
            ],
            options={
                'db_table': 'Pattern_Source',
            },
        ),
        migrations.CreateModel(
            name='Matched',
            fields=[
                ('MAT_id', models.AutoField(primary_key=True, serialize=False)),
                ('MAT_graph', models.BinaryField()),
                ('MAT_order', models.IntegerField()),
                ('MAT_cost', models.FloatField(db_index=True)),
                ('MAT_ideal_cost', models.FloatField()),
                ('MAT_ideal_cost_saving', models.FloatField()),
                ('MAT_comment', models.TextField(null=True)),
                ('MAT_png', models.BinaryField()),
                ('MAT_match_method_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mining.match_method_type')),
                ('MAT_pattern', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mining.pattern')),
                ('MAT_topology', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mining.topology')),
            ],
            options={
                'db_table': 'Matched',
            },
        ),
        migrations.CreateModel(
            name='Match_Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MK_key', models.TextField()),
                ('MK_key_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mining.key_type')),
                ('MK_match', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mining.matched')),
            ],
            options={
                'db_table': 'Match_Key',
            },
        ),
    ]
