# Generated by Django 3.1 on 2020-08-26 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0002_auto_20200826_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Method_Type',
            fields=[
                ('MMT_id', models.AutoField(primary_key=True, serialize=False)),
                ('MMT_type_desc', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'Match_Method_Type',
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('PAT_id', models.AutoField(primary_key=True, serialize=False)),
                ('PAT_key', models.CharField(db_index=True, default='the key string of the pattern', max_length=4096)),
                ('PAT_graph', models.BinaryField()),
                ('PAT_order', models.IntegerField()),
                ('PAT_name', models.CharField(max_length=45, null=True)),
                ('PAT_desc', models.CharField(max_length=4096, null=True)),
                ('PAT_png', models.BinaryField()),
            ],
            options={
                'db_table': 'Pattern',
            },
        ),
        migrations.CreateModel(
            name='Matched',
            fields=[
                ('MAT_id', models.AutoField(primary_key=True, serialize=False)),
                ('MAT_graph', models.BinaryField()),
                ('MAT_order', models.IntegerField()),
                ('MAT_cost', models.FloatField(db_index=True)),
                ('MAT_ideal_cost', models.FloatField()),
                ('MAT_ideal_cost_saving', models.FloatField()),
                ('MAT_comment', models.TextField(null=True)),
                ('MAT_png', models.BinaryField()),
                ('MAT_match_method_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mining.match_method_type')),
                ('MAT_pattern', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mining.pattern')),
                ('MAT_topology', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mining.topology')),
            ],
            options={
                'db_table': 'Matched',
            },
        ),
    ]
