# Generated by Django 3.1 on 2020-08-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0004_auto_20200826_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Method_Type',
            fields=[
                ('MMT_id', models.AutoField(primary_key=True, serialize=False)),
                ('MMT_type_desc', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'Match_Method_Type',
            },
        ),
    ]
