# Generated by Django 3.1 on 2020-08-26 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0005_match_method_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matched',
            fields=[
                ('MAT_id', models.AutoField(primary_key=True, serialize=False)),
                ('MAT_graph', models.BinaryField()),
                ('MAT_order', models.IntegerField()),
                ('MAT_cost', models.FloatField(db_index=True)),
                ('MAT_ideal_cost', models.FloatField()),
                ('MAT_ideal_cost_saving', models.FloatField()),
                ('MAT_comment', models.TextField(null=True)),
                ('MAT_png', models.BinaryField()),
                ('MAT_match_method_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mining.match_method_type')),
                ('MAT_pattern', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mining.pattern')),
                ('MAT_topology', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mining.topology')),
            ],
            options={
                'db_table': 'Matched',
            },
        ),
    ]
