# Generated by Django 3.1 on 2020-08-26 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0006_matched'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key_Type',
            fields=[
                ('KT_id', models.AutoField(primary_key=True, serialize=False)),
                ('KT_key_desc', models.TextField(default='desc of key type')),
            ],
            options={
                'db_table': 'Key_Type',
            },
        ),
        migrations.CreateModel(
            name='Match_Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MK_key', models.TextField()),
                ('MK_key_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mining.key_type')),
                ('MK_match', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mining.matched')),
            ],
            options={
                'db_table': 'Match_Key',
            },
        ),
    ]
