# Generated by Django 3.1 on 2020-08-26 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0007_key_type_match_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern_Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PS_pattern', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mining.pattern')),
                ('PS_topology', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mining.topology')),
            ],
            options={
                'db_table': 'Pattern_Source',
            },
        ),
    ]
